///////////////////////////////////////////////////////////
//  RobotCommand.h
//  Implementation of the Class RobotCommand
//  Generated by Enterprise Architect
//  Created on:      17-Apr-2011 5:15:04 PM
//  Original author: peter.finn
///////////////////////////////////////////////////////////

#ifndef ROBOTCOMMAND_H
#define ROBOTCOMMAND_H

#include <string>
using std::string;

class RobotCommand
{
public:
	RobotCommand();
	RobotCommand(char cmd, int cycles);
	RobotCommand & operator=( const RobotCommand & cmd );
	RobotCommand( const RobotCommand & cmd );
	~RobotCommand();

	//getters
	char getCode();
	int getCycles();

private:
	//A char which is either f,b,l,r meaning forward, back, left or right respectivly.
	//Can also be s for stop.
	char m_code;
	//The amount of time in miliseconds that the robot will set the motors.
	int m_cycles;	

};

#endif